<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Settings extends Model
{
    use \App\Traits\CacheClearing, HasFactory;

    protected $fillable = [
        'address',
        'phone',
        'phone_two',
        'phone_three',
        'dial_up',
        'whatsapp_number',
        'contact_phone_plus',
        'messenger_username',
        'imo_number',
        'email',
        'email_two',
        'marque_text',
        'marque_status',
        'sms_status',
        'fb_link',
        'twitter_link',
        'yt_link',
        'insta_link',
        'copyright',
        'logo',
        'favicon',
        'currency',
        'bkash',
        'fb_pixel',
        'about_us',
        'delivery_policy',
        'return_policy',
        'google_sheet',
        'orders_per_hour_limit',
        'orders_per_day_limit',
        'whatsapp_from_phone_number_id',
        'whatsapp_token',
        'whatsapp_notification_enabled_processing',
        'whatsapp_template_name_processing',
        'whatsapp_notification_enabled_pending_delivery',
        'whatsapp_template_name_pending_delivery',
        'whatsapp_notification_enabled_on_hold',
        'whatsapp_template_name_on_hold',
        'whatsapp_notification_enabled_cancel',
        'whatsapp_template_name_cancel',
        'whatsapp_notification_enabled_completed',
        'whatsapp_template_name_completed',
        'whatsapp_notification_enabled_pending_payment',
        'whatsapp_template_name_pending_payment',
        'whatsapp_notification_enabled_on_delivery',
        'whatsapp_template_name_on_delivery',
        'whatsapp_notification_enabled_no_response1',
        'whatsapp_template_name_no_response1',
        'whatsapp_notification_enabled_no_response2',
        'whatsapp_template_name_no_response2',
        'whatsapp_notification_enabled_courier_hold',
        'whatsapp_template_name_courier_hold',
        'whatsapp_notification_enabled_order_return',
        'whatsapp_template_name_order_return',
        'sms_api_key',
        'sms_api_secret',
        'sms_sender_id',
        'sms_api_url',
        'sms_notification_enabled_processing',
        'sms_template_processing',
        'sms_notification_enabled_pending_delivery',
        'sms_template_pending_delivery',
        'sms_notification_enabled_on_hold',
        'sms_template_on_hold',
        'sms_notification_enabled_cancel',
        'sms_template_cancel',
        'sms_notification_enabled_completed',
        'sms_template_completed',
        'sms_notification_enabled_pending_payment',
        'sms_template_pending_payment',
        'sms_notification_enabled_on_delivery',
        'sms_template_on_delivery',
        'sms_notification_enabled_no_response1',
        'sms_template_no_response1',
        'sms_notification_enabled_no_response2',
        'sms_template_no_response2',
        'sms_notification_enabled_courier_hold',
        'sms_template_courier_hold',
        'sms_notification_enabled_order_return',
        'sms_template_order_return',
        'forwarding_enabled',
        'forwarding_master_domain',
        'forwarding_master_secret',
    ];
}
